In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Part 1 - Data preprocessing

In [2]:
# Importing the dataset
dataset = pd.read_csv(r'Churn_Modelling.csv')

In [3]:
dataset.shape

(10000, 14)

In [4]:
# Matrix of features
X = dataset.iloc[:, 3:13].values
# Target column
y = dataset.iloc[:, 13].values

In [5]:
X.shape

(10000, 10)

In [6]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y.shape

(10000,)

In [8]:
# Encoding categorical data
# Categorical columns - "Country" and "Gender"
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# labelencoder for "Country"
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [9]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
# labelencoder for "Gender"
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_1.fit_transform(X[:, 2])

In [11]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [12]:
# One hot encoding for "Country" since this column is not ordinal
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

In [13]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [14]:
# Remove 1st column - dummy variable trap
X = X[:, 1:]

In [15]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [16]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

Part 2 - Build ANN

In [19]:
import keras

C:\Users\Shrivatav\Anaconda3\lib\site-packages\h5py\__init__.py:72: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Using TensorFlow backend.


In [20]:
from keras.models import Sequential
from keras.layers import Dense

In [21]:
# Initialisng the ANN
# We define our ANN as a sequence of layers
classifier = Sequential()

In [22]:
# Adding input layer and first hidden layer
classifier.add(Dense(output_dim = 6, init = "uniform", activation = "relu", input_dim = 11))

C:\Users\Shrivatav\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [23]:
# Add second hidden layer
classifier.add(Dense(output_dim = 6, init = "uniform", activation = "relu"))

C:\Users\Shrivatav\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [24]:
# Add output layer
classifier.add(Dense(output_dim = 1, init = "uniform", activation = "sigmoid"))

C:\Users\Shrivatav\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [25]:
# Compile the ANN
classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [26]:
# Fit classifier to training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

C:\Users\Shrivatav\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.4814 - acc: 0.7957
Epoch 2/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.4264 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.4211 - acc: 0.8009: 0s - loss: 0.4372
Epoch 4/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.4180 - acc: 0.8237
Epoch 5/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4156 - acc: 0.8275
Epoch 6/100
8000/8000 [==============================] - 1s 121us/step - loss: 0.4141 - acc: 0.8294
Epoch 7/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.4124 - acc: 0.8304
Epoch 8/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.4114 - acc: 0.8332
Epoch 9/100
8000/8000 [==============================] - 1s 101us/step - loss: 0.4102 - acc: 0.8326
Epoch 10/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.40

8000/8000 [==============================] - 1s 94us/step - loss: 0.3962 - acc: 0.8364
Epoch 83/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.3961 - acc: 0.8365
Epoch 84/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.3961 - acc: 0.8366
Epoch 85/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.3951 - acc: 0.8382
Epoch 86/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.3955 - acc: 0.8371
Epoch 87/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.3954 - acc: 0.8352
Epoch 88/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.3955 - acc: 0.8354
Epoch 89/100
8000/8000 [==============================] - 1s 99us/step - loss: 0.3956 - acc: 0.8364
Epoch 90/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.3952 - acc: 0.8369
Epoch 91/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3960 - acc: 0.8375
Epoch 92/10

In [27]:
# We get training accuracy of ~ 86 percent

# Make predictions on test data
y_pred = classifier.predict(X_test)

In [28]:
y_pred

array([[0.20546979],
       [0.40266767],
       [0.18675613],
       ...,
       [0.19515549],
       [0.17795452],
       [0.11841843]], dtype=float32)

In [29]:
# Convert to 0,1 encoding
y_pred = (y_pred > 0.5)

In [30]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [31]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [32]:
cm

array([[1543,   52],
       [ 254,  151]], dtype=int64)

In [33]:
acc = (cm[0,0] + cm[1,1])/2000
print(acc)

0.847


In [34]:
# We get ~86% accuracy on test data!

Part 3 - Make predictions and evaluate the model
Use ANN to make prediction for a customer with the following attributes:
- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40 years old
- Tenure: 3 years
- Balance: 60000 USD
- Number of Products 2
- Does this customer have a credit card ? Yes
- Is this customer an Active Member: Yes
- Estimated Salary: 50000 USD

In [35]:
# Create single row array for the given attributes
new_customer = np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]) # using single [] constructs vertical column array
# Scale this record on the same scale used for training data
new_customer_scaled = sc.transform(new_customer)
new_customer_pred = classifier.predict(new_customer_scaled)
new_customer_pred = (new_customer_pred > 0.5)
new_customer_pred

array([[False]])

Part 4 - Improving the model

In [36]:
# Use KerasClassifier to wrap k-fold cross validation from scikit-learn into our keras model
from keras.wrappers.scikit_learn import KerasClassifier

In [37]:
from sklearn.model_selection import cross_val_score

In [38]:
# Function for building ANN classifier - to be used in KerasClassifier parameter 'build_fn'
def build_classifier():
    classifier = Sequential()
    # Add input layer and first hidden layer
    classifier.add(Dense(output_dim = 6, init = "uniform", activation = "relu", input_dim = 11))
    # Add second hidden layer
    classifier.add(Dense(output_dim = 6, init = "uniform", activation = "relu"))
    # Add output layer
    classifier.add(Dense(output_dim = 1, init = "uniform", activation = "sigmoid"))
    # Compile the ANN
    classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
    return classifier

In [39]:
# Build a classifier using 10-fold cv and find accuracies
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, nb_epoch = 100)

In [46]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = 1) # n_jobs = -1 uses all CPUs

C:\Users\Shrivatav\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """
C:\Users\Shrivatav\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  import sys
C:\Users\Shrivatav\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  if __name__ == '__main__':


Epoch 1/1
800/800 [==============================] - 0s 377us/step
Epoch 1/1
800/800 [==============================] - 0s 384us/step
Epoch 1/1
800/800 [==============================] - 0s 358us/step
Epoch 1/1
800/800 [==============================] - 1s 629us/step
Epoch 1/1
800/800 [==============================] - 0s 611us/step
Epoch 1/1
800/800 [==============================] - 0s 399us/step
Epoch 1/1
800/800 [==============================] - 0s 407us/step
Epoch 1/1
800/800 [==============================] - 0s 430us/step
Epoch 1/1
800/800 [==============================] - 0s 494us/step
Epoch 1/1
800/800 [==============================] - 0s 496us/step


In [41]:
# Compute mean and variance of all accuracy values
meann = accuracies.mean()
variance = accuracies.std()

In [43]:
meann

0.7966249968856574

In [44]:
variance

0.010444046518704023

In [45]:
accuracies

array([0.78625   , 0.79      , 0.805     , 0.7825    , 0.81625   ,
       0.81      , 0.7875    , 0.79375   , 0.8       , 0.79499999])

In [47]:
# Improving the model by using dropout regularization
from keras.layers import Dropout

In [50]:
# Function for building ANN classifier - to be used in KerasClassifier parameter 'build_fn'
# Using optimizer as a variable - enables us to use different values in GridSearch
def build_classifier_modified(optimizer):
    classifier = Sequential()
    # Add input layer and first hidden layer
    classifier.add(Dense(output_dim = 6, init = "uniform", activation = "relu", input_dim = 11))
    # Add second hidden layer
    classifier.add(Dense(output_dim = 6, init = "uniform", activation = "relu"))
    # Add output layer
    classifier.add(Dense(output_dim = 1, init = "uniform", activation = "sigmoid"))
    # Compile the ANN
    classifier.compile(optimizer = optimizer, loss = "binary_crossentropy", metrics = ["accuracy"])
    return classifier

In [ ]:
# Adding input layer and first hidden layer with Dropout
classifier.add(Dense(output_dim = 6, init = "uniform", activation = "relu", input_dim = 11))
classifier.add(Dropout(p = 0.1))

In [ ]:
# Add second hidden layer
classifier.add(Dense(output_dim = 6, init = "uniform", activation = "relu"))
classifier.add(Dropout(p = 0.1))

In [48]:
# Tuning hyperparameters using GridSearch
from sklearn.model_selection import GridSearchCV

In [51]:
classifier_new = KerasClassifier(build_fn = build_classifier_modified)

In [52]:
# Dictionary of hyperparameters
parameters = {
    "batch_size" : [25, 32],
    "nb_epoch" : [100, 500],
    "optimizer" : ["adam", "rmsprop"]
}

In [53]:
grid_search = GridSearchCV(estimator = classifier_new, param_grid = parameters, scoring = "accuracy", cv = 10)

In [54]:
grid_search = grid_search.fit(X_train, y_train)

C:\Users\Shrivatav\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  
C:\Users\Shrivatav\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  
C:\Users\Shrivatav\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.


Epoch 1/1
7200/7200 [==============================] - 2s 326us/step - loss: 0.5495 - acc: 0.7965
Epoch 1/1
7200/7200 [==============================] - 2s 248us/step - loss: 0.5512 - acc: 0.7965
Epoch 1/1
7200/7200 [==============================] - 2s 230us/step - loss: 0.5587 - acc: 0.7936
Epoch 1/1
7200/7200 [==============================] - 2s 274us/step - loss: 0.5595 - acc: 0.7962
Epoch 1/1
7200/7200 [==============================] - 3s 367us/step - loss: 0.5755 - acc: 0.7933
Epoch 1/1
7200/7200 [==============================] - 2s 258us/step - loss: 0.5779 - acc: 0.7925
Epoch 1/1
7200/7200 [==============================] - 2s 275us/step - loss: 0.5760 - acc: 0.7953
Epoch 1/1
7200/7200 [==============================] - 2s 260us/step - loss: 0.6096 - acc: 0.7943
Epoch 1/1
7200/7200 [==============================] - 2s 328us/step - loss: 0.5599 - acc: 0.7951
Epoch 1/1
7200/7200 [==============================] - 2s 276us/step - loss: 0.6004 - acc: 0.7940
Epoch 1/1
7200/7200 

In [55]:
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

In [56]:
best_accuracy

0.796

In [57]:
best_parameters

{'batch_size': 25, 'nb_epoch': 100, 'optimizer': 'adam'}